# shell
brew "fish"
brew "bash"
brew "shellcheck"

# programs
brew "tmux"
brew "neovim"
brew "vim"
brew "git"
brew "nnn"
brew "fzf"
brew "curl"
brew "htop"
brew "links"
brew "pass"

# mail
brew "neomutt"
brew "isync"
brew "msmtp"

# utilities
brew "ripgrep"
brew "trash-cli"
brew "awscli"
brew "tldr"
brew "asciinema"
brew "youtube-dl"
brew "ffmpeg"
brew "imageoptim-cli"

# programming languages
brew "rust"
brew "gcc"
brew "node"
brew "python"
brew "yarn"
brew "serverless"

if OS.mac?
    # gnu coreutils
    brew "coreutils"
    brew "findutils"
    brew "gnu-tar"
    brew "gnu-sed"
    brew "gawk"
    brew "gnutls"
    brew "gnu-indent"
    brew "gnu-getopt"
    brew "grep"

    # gui
    tap "homebrew/cask-versions"
    cask "alacritty"
    cask "firefox-developer-edition"
    cask "alfred"
    cask "pock"
    cask "macs-fan-control"
    cask "karabiner-elements"
end
