#!/bin/bash

# todo: https://github.com/FiloSottile/age

filename="$1/$(hostname)_$(date -I).tar"

read -p "Are you sure you want to write backup to $filename? " -n 1
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
fi

dpkg --get-selections "*" > ~/.packages
mbsync -a

sudo tar cvf $filename /home /etc /var
