#!/bin/sh

export RESTIC_PASSWORD=$(pass restic/$(hostname))

for REPO_PREFIX in "$@"; do
	restic -r "$REPO_PREFIX$(hostname)" backup "$HOME" \
		--exclude="$HOME/.cache" \
		--exclude="$HOME/.npm" \
		--exclude="$HOME/.go" \
		--exclude="$HOME/.thumbnails" \
		--exclude="$HOME/.mozilla" \
		--exclude="$HOME/.gradle" \
		--exclude="$HOME/.cargo" \
		--exclude="$HOME/.rustup"

	restic -r "$REPO_PREFIX$(hostname)" forget \
		--keep-daily 7 \
		--keep-weekly 5 \
		--keep-monthly 12 \
		--keep-yearly 75 \
		--prune
done
