#!/bin/bash

set -e

filename="$1/$(hostname)_$(date -I).tar"

# check
read -p "Are you sure you want to write backup to $filename (y/n)? " -n 1
echo
[[ $REPLY =~ ^[Yy]$ ]] || exit 1

# sync
which dpkg > /dev/null   && dpkg --get-selections "*" > ~/.packages
which mbsync > /dev/null && mbsync -a

# backup
sudo tar cvf $filename /home /etc /var
