#!/bin/sh

set -e

dir=$1/$(hostname)
test -d $dir || sudo mkdir $dir

# sync
[ -n "$SKIP_SYNC" ] || (
	which dpkg > /dev/null && dpkg --get-selections "*" > ~/.packages
	which mbsync > /dev/null && mbsync -a
)

# update live version
sudo rsync -ah --delete --info=progress2 /home /etc /var $dir/live

# delete old snapshot
ls $dir/*snapshot_* | sort | head -n -3 | xargs -pr sudo rm

# create new snapshot
(cd $dir/live && sudo tar cf $dir/snapshot_$(date -I).tar --totals .)
