#!/bin/sh

deps="electrum qrencode open"
for cmd in $(echo $deps | tr ' ' '\n'); do
	command -v $cmd > /dev/null || { echo please install $cmd; exit 1; }
done

seed=$(electrum -o make_seed --nbits 256)
electrum -o restore "$seed" -w tmpwallet.json > /dev/null
pubkey=$(jq -r .addresses.receiving[0] tmpwallet.json)
rm tmpwallet.json

cat << EOF > tmpdoc.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>btc-gift</title>
  </head>
  <body>
    <style>
      @import url("https://rsms.me/inter/inter.css");
      html {
        font-family: "Inter", sans-serif;
      }
      @supports (font-variation-settings: normal) {
        html {
          font-family: "Inter var", sans-serif;
        }
      }

      * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
      }

      body {
        line-height: 1.5;
      }

      h2 {
        margin-top: 12px;
      }

      .blank {
        background-color: #ddd;
        width: 100%;
        height: 300px;
        border-radius: 10px;
        margin-bottom: 32px;
      }

      .public-key,
      .seed-words {
        font-family: monospace;
        font-size: 18px;
      }

      .seed-words {
        list-style-type: none;
        display: flex;
        flex-wrap: wrap;
        align-items: center;
      }

      .seed-words > * {
        width: 25%;
      }
    </style>

    <div class="blank"></div>

    <h1>Pročitaj me... kasnije</h1>
    <p>
      Pozdrav, nadam se da ti je rođendanska zabava bila super i da nisam
      predugo skupljao prašinu zaboravljen na polici (znam da jesam). Ne brini,
      opraštam ti, znam i ja, iako sam samo papir, životne obaveze i teškoće
      preće su od nekog čudnog rođendanskog poklona. Ipak drago mi je što me
      čitaš jer to znači da te ipak zanima što je na meni napisano. Moj zadatak
      je naučiti te kako da koristiš svoj Bitcoin novčanik (a nisi ni znao/la da
      ga imaš!)
    </p>

    <h2>Bitcoin</h2>
    <p>
      Bitcoin je jedna od onih stvari za koju su svi čuli zbog velikog rasta
      vrijednosti ali rijetko tko razumije kako se njime služiti, te zašto uopće
      postoji. Za početak malo povijesti (znam, znam, ne voliš povijest, skratit
      ću) Bitcoin je digitalna valuta koju je napravio nepoznati autor pod
      pseudonimom Satoshi Nakamoto 2008. godine, a glavna prednost mu je rad bez
      središnje institucije npr. banke (decentraliziranost).
    </p>

    <h2>Novčanik</h2>
    <p>
      Bitcoin novčanik možeš zamisliti kao bankovni račun, samo sa svojstvom
      decentraliziranosti. Nitko te ne može ovršiti, stopirati tvoju transakciju
      ili blokirati tvoj novac sa računa. Korištenje je nešto drugačije, odvija
      se pomoću javnog i privatnog ključa.
    </p>

    <h2>Javni ključ</h2>
    <div style="display: flex">
      <p>
        Javni ključ je IBAN za tvoj decentralizirani bankovni račun. Netko tko
        ti želi poslati Bitcoin mora znati tvoj javni ključ. Kako i samo ime
        kaže javni ključ sigurno je dijeliti, kao e-mail adresu, pa ga ne moraš
        skrivati. Javni ključ možeš koristiti i za provjeru stanja u novčaniku.
        Probaj skenirati ovaj QR kod.
        <br />
        Tvoj javni ključ:
        <span class="public-key">
          $pubkey
        </span>
      </p>
      <div style="margin-left: 30px">
        $(echo https://www.blockchain.com/btc/address/$pubkey | qrencode -t svg)
      </div>
    </div>

    <h2>Privatni ključ</h2>
    <p>
      Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maxime sed
      delectus eius, cumque, ipsa laborum non magni facere repudiandae error,
      eaque incidunt pariatur repellat velit voluptas est! Commodi, velit
      dolorem.
    </p>
    <div style="display: flex">
      <ul class="seed-words">
        <li>$(echo -n $seed | sed 's/ /\n<li>/g')
      </ul>
      <div>
        $(echo -n $seed | qrencode -t svg)
      </div>
    </div>

    <script>
      window.print()
    </script>
  </body>
</html>
EOF
open tmpdoc.html
sleep 3
rm tmpdoc.html
