#!/bin/sh

set -ex

app=$1

yarn create react-app $app

cd $app

grep -vi "vitals\|performance" src/index.js |\
sed 's/\.\/App/\.\/components\/App/g' > src/index.jsx

mkdir src/components src/constants src/services src/utils

# todo: add styled components and react router

mkdir src/components/App
cat > src/components/App/index.jsx <<EOF
import React from "react";

const App = () => {
  return <div>app</div>;
}

export default App;
EOF

rm README.md
rm public/favicon.ico public/logo*.png public/manifest.json
rm src/App.css src/logo.svg src/*.js
[ -d .git ] && rm -r .git

cd ..
mv $app/* $app/.gitignore .
rmdir $app
