#!/bin/sh

dir=~/.cache/fesb-elearning-promjene

mkdir -p $dir

if [ "$#" -lt 3 ]; then 
	echo "Usage: fesb-elearning-promjene [username] [password] [path]..."
	exit 1
fi

username=$1; shift
password=$1; shift

cookie=$(
	curl 'https://elearning.fesb.unist.hr/login/index.php' -X POST \
	-F "username=$username" -F "password=$password" -s -D - \
	| grep 'MoodleSession=' \
	| tail -n 1 \
	| cut -c 5-
)

for path in "$@"; do
	tmp=$(mktemp)
	curl "https://elearning.fesb.unist.hr/$path" -H "$cookie" > $tmp

	content_start_line=$(grep -n 'id="page"' $tmp | cut -d: -f1)
	content_end_line=$(grep -n 'id="nav-drawer"' $tmp | cut -d: -f1)

	cat $tmp \
	| head -n $content_end_line \
	| tail -n +$content_start_line \
	| pandoc -f html -t markdown_strict
done
