#!/bin/sh

dir=~/.cache/fesb-elearning-promjene

mkdir -p $dir

if [ "$#" -lt 3 ]; then 
	echo "Usage: fesb-elearning-promjene [username] [password] [course]..."
	exit 1
fi

username=$1; shift
password=$1; shift

cookie=$(
	curl 'https://elearning.fesb.unist.hr/login/index.php' -X POST \
	-F "username=$username" -F "password=$password" -s -D - \
	| grep 'MoodleSession=' \
	| tail -n 1 \
	| cut -c 5- \
	| cut -d';' -f1
)

for course in "$@"; do
	tmp_html=$(mktemp)
	tmp_plain=$(mktemp)
	curl "https://elearning.fesb.unist.hr/course/view.php?id=$course" \
	-H "$cookie" -s > $tmp_html

	filename=$dir/$(echo $course | md5sum | cut -d' ' -f1)
	content_start_line=$(grep -n 'id="page"' $tmp_html | cut -d: -f1)
	content_end_line=$(grep -n 'id="sb-3"' $tmp_html | cut -d: -f1)

	cat $tmp_html \
	| head -n $content_end_line \
	| tail -n +$content_start_line \
	| pandoc -f html -t plain \
	> $tmp_plain

	if [ -f "$filename" ]; then
		cmp -s $filename $tmp_plain || head -n 1 $tmp_plain
		diff $filename $tmp_plain
		cmp -s $filename $tmp_plain || echo
	fi

	cat $tmp_plain > $filename

	rm $tmp_html $tmp_plain
done
