#!/bin/sh

curl -s https://slobodnadalmacija.hr/split |
grep article-link |
head -1 |
sed -e 's/<a /\n<a /g' |
sed -e 's/<a .*href=['"'"'"]//' -e 's/["'"'"'].*$//' -e '/^$/ d' |
sed 's/^/https:\/\/slobodnadalmacija.hr/'

echo

curl -s https://slobodnadalmacija.hr/vijesti |
grep article-link |
head -1 |
sed -e 's/<a /\n<a /g' |
sed -e 's/<a .*href=['"'"'"]//' -e 's/["'"'"'].*$//' -e '/^$/ d' |
sed 's/^/https:\/\/slobodnadalmacija.hr/'

echo

curl -s https://www.ft.com/technology |
grep js-teaser-heading-link |
sed -e 's/<a /\n<a /g' |
sed -e 's/<a .*href=['"'"'"]//' -e 's/["'"'"'].*$//' -e '/^$/ d' |
grep content |
uniq |
head -1 |
sed 's/^/https:\/\/archive.today\/o\/https:\/\/www.ft.com/'

echo

curl -s https://www.ft.com/companies |
grep js-teaser-heading-link |
sed -e 's/<a /\n<a /g' |
sed -e 's/<a .*href=['"'"'"]//' -e 's/["'"'"'].*$//' -e '/^$/ d' |
grep content |
uniq |
head -1 |
sed 's/^/https:\/\/archive.today\/o\/https:\/\/www.ft.com/'
