#!/bin/sh
#
# recursive git status

for repo in $(find . -type d -name .git -prune -exec dirname {} \;); do
	printf "%-20s" $repo
	num=$(git -C "$repo" log --branches --not --remotes --oneline | wc -l) && test $num -gt 0 && printf "\t%s unpushed" $num
	num=$(git -C "$repo" ls-files --others --exclude-standard | wc -l)     && test $num -gt 0 && printf "\t%s untracked" $num
	num=$(git -C "$repo" diff --name-only | wc -l)                         && test $num -gt 0 && printf "\t%s modified" $num
	num=$(git -C "$repo" diff --name-only --cached | wc -l)                && test $num -gt 0 && printf "\t%s staged" $num
	printf "\n"
done
