#!/bin/sh

if [ -n "$(git status --porcelain)" ]; then
	printf "\e[00;31mmodified\e[0m\n"
	exit 1
fi

if [ -n "$(git log "@{push}..")" ]; then
	printf "\e[00;33munpushed\e[0m\n"
	exit 2
fi

echo clean
