#!/bin/sh
#
# recursive git status

for repo in $(find . -type d -name .git -prune -exec dirname {} \;); do
	printf "%-20s" $repo
	up=$(git -C "$repo" log --branches --not --remotes --oneline | wc -l); [ $up -gt 0 ] && printf "\t%s unpushed"  $up
	ut=$(git -C "$repo" ls-files --others --exclude-standard | wc -l);     [ $ut -gt 0 ] && printf "\t%s untracked" $ut
	mo=$(git -C "$repo" diff --name-only | wc -l);                         [ $mo -gt 0 ] && printf "\t%s modified"  $mo
	st=$(git -C "$repo" diff --name-only --cached | wc -l);                [ $st -gt 0 ] && printf "\t%s staged"    $st
	printf "\n"
done
