#!/bin/sh
#
# license:
# pf is in the public domain. if it breaks, you get to keep both pieces.
#
# description:
# script patches file content without overwriting content that was in file
# before running the script. it can also handle multiple script runs with
# same or updated file contents.
#
# how to use:
# pf <filename> <comment-delimiter> << EOF
# <file-content>
# EOF

patch=$(mktemp)
patched_file=$(mktemp)

file=$1
comment_delimiter=$2
cat > $patch

comment_start="$comment_delimiter patched by pf; start"
comment_end="$comment_delimiter patched by pf; end"

touch $file

if grep -q "$comment_start" $file && grep -q "$comment_end" $file; then
	head -n $(grep -n "$comment_start" $file | cut -d: -f1) $file
	cat $patch
	tail -n +$(grep -n "$comment_end" $file | cut -d: -f1) $file
else
	cat $file
	echo
	echo $comment_start
	cat $patch
	echo $comment_end
fi > $patched_file

mv $patched_file $1
rm $patch
