#!/bin/sh

dir=~/.cache/svkst-otvoreni-datumi
out=$dir/output
hst=$dir/history

mkdir -p $dir
touch $hst

curl 'https://www.svkst.unist.hr/wp-admin/admin-ajax.php' \
	-H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
	--data-raw 'action=wbk_prepare_service_data&service=8' -s \
	| jq -r .disabilities \
	| tr ";" "\n" \
	| awk -F',' '{print $1"-"$2+1"-"$3}' \
	| xargs -i date -d {} +%Y-%m-%d\ %a \
	> $out

while read line; do
	if ! grep -q "$line" $hst; then
		echo $line
		echo $line >> $hst
	fi
done < $out
