#!/bin/sh

dir=~/.cache/svkst-otvoreni-datumi
out=$dir/output
out_prev=$dir/prev_output

mkdir -p $dir
[ -s $out ] && cp $out $out_prev

curl 'https://www.svkst.unist.hr/wp-admin/admin-ajax.php' \
	-H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
	--data-raw 'action=wbk_prepare_service_data&service=8' -s \
	| jq -r .disabilities \
	| tr ";" "\n" \
	| awk -F',' '{print $1"-"$2+1"-"$3}' \
	| xargs -i date -d {} +%Y-%m-%d\ %a \
	> $out

if [ -f $out_prev ]; then
	comm -13 $out_prev $out
	rm $out_prev
else
	cat $out
fi
