# editorconfig
hook global WinCreate ^[^*]+$ %{editorconfig-load}

# lsp
eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(go|javascript) %{
	lsp-enable-window
	hook window BufWritePre .* lsp-formatting-sync
}
lsp-auto-hover-enable
lsp-auto-hover-insert-mode-enable

# comments
map global normal '#' :comment-line<ret>

# tab
hook global InsertCompletionShow .* %{
	try %{
		execute-keys -draft 'h<a-K>\h<ret>'
		map window insert <tab> <c-n>
		map window insert <s-tab> <c-p>
	}
}
hook global InsertCompletionHide .* %{
	unmap window insert <tab> <c-n>
	unmap window insert <s-tab> <c-p>
}

# clipboard
map global normal <a-y> '<a-|>xsel --input --clipboard<ret>'
map global normal <a-p> '<a-!>xsel --output --clipboard<ret>'
map global normal <a-P> '!xsel --output --clipboard<ret>'

# grep
set global grepcmd 'rg --column'

# find
def find -params 1 -shell-script-candidates %{ rg --files } %{ edit %arg{1} }
alias global f find

# line numbers
addhl global/ number-lines -separator ' '

# column
addhl global/ column 81 default,rgb:333333

# whitespace
addhl global/ show-whitespaces -lf ' ' -spc ' '

# colorscheme
colorscheme tomorrow-night

# highlight keywords
addhl global/ regex \b(TODO|FIXME|NOTE)\b 0:+rb

# highlight matching brackets
addhl global/ show-matching
