#!/bin/sh

echo hn
curl -s "https://hn.algolia.com/api/v1/search?numericFilters=created_at_i>$(date -d "-1 day" +%s)&hitsPerPage=3" |
jq -r .hits[].objectID |
sed 's/^/https:\/\/news.ycombinator.com\/item?id=/'

echo

echo lobsters
curl -s https://lobste.rs/top/1d |
grep "<a href=\"/s/" |
head -6 |
sed -e 's/.*href=['"'"'"]//' -e 's/["'"'"'].*$//' |
uniq |
sed 's/^/https:\/\/lobste.rs/'

echo

echo r/programming
curl -sA 'getnews' https://old.reddit.com/r/programming/top.json?limit=3 |
jq -r .data.children[].data.permalink |
sed 's/^/https:\/\/old.reddit.com/'

echo

echo r/devops
curl -sA 'getnews' https://old.reddit.com/r/devops/top.json?limit=3 |
jq -r .data.children[].data.permalink |
sed 's/^/https:\/\/old.reddit.com/'

echo

echo ft technology
curl -s https://www.ft.com/technology |
grep js-teaser-heading-link |
sed -e 's/<a /\n<a /g' |
sed -e 's/<a .*href=['"'"'"]//' -e 's/["'"'"'].*$//' -e '/^$/ d' |
grep content |
uniq |
head -3 |
sed 's/^/https:\/\/archive.is\/newest\/https:\/\/www.ft.com/'

echo

echo ft companies
curl -s https://www.ft.com/companies |
grep js-teaser-heading-link |
sed -e 's/<a /\n<a /g' |
sed -e 's/<a .*href=['"'"'"]//' -e 's/["'"'"'].*$//' -e '/^$/ d' |
grep content |
uniq |
head -3 |
sed 's/^/https:\/\/archive.is\/newest\/https:\/\/www.ft.com/'
