#!python

naziv = input('naziv serije: ')
broj_epizoda = input('broj epizoda: ').split(',')
ep_dan = int(input('broj epizoda dnevno: '))

for idx, broj_epizoda_u_sezoni in enumerate(broj_epizoda):
    for ep in range(1, int(broj_epizoda_u_sezoni)+1, ep_dan):
        if ep_dan > 1:
            e = str(ep)
            for br in range(ep+1, ep+ep_dan):
                if br <= int(broj_epizoda_u_sezoni):
                    e = e + '+' + str(br)
            print(f'{naziv} s{idx+1}e{e}')
        else:
            print(f'{naziv} s{idx+1}e{ep}')
