#!/usr/bin/env bash
#
# Cloudflare Dynamic DNS

token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
zone=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
record=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
name=rpi.bartol.dev
ip=$(curl -s icanhazip.com)

if [ "$ip" == "$(cat ip.txt)" ]; then
	exit 0
fi
echo $ip > ip.txt

curl -X PUT "https://api.cloudflare.com/client/v4/zones/$zone/dns_records/$record" \
	-H "Authorization: Bearer $token" \
	-H "Content-Type: application/json" \
	--data "{\"type\":\"A\",\"name\":\"$name\",\"content\":\"$ip\",\"proxied\":true}"

# crontab -e
# */15 * * * * /home/bartol/scripts/rpi/ddns
