#!/bin/bash

home=$(pwd)
dirs=$(find . -type d -name .git -maxdepth "${1:-2}")

for dir in $dirs
do
    dir=${dir//.git/}
    cd "$dir" || exit

    if [[ -n $(git status -s) ]]
    then
        printf "\n\e[36m%s\e[0m\n" "$dir"
        git status -s
    fi

    cd "$home" || exit
done
